version: '2'
services:
  postgres:
    image: postgres
    volumes:
       - db_data:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: "db_name"
        POSTGRES_USER: "user"
        POSTGRES_PASSWORD: "pw"
        POSTGRES_PORT: 5432
    networks:
      - backend

  web:
    build: .
    command: mix phx.server
    ports:
      - "80:4000"
    depends_on:
      - postgres
    environment:
      - MIX_ENV=prod
      - PORT=4000
    networks:
      - backend

volumes:
    db_data:

networks:
    backend:
