version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    command: mix phx.server
    volumes:
      - .:/app
    ports:
      - "80:4000"
    depends_on:
      - db
    environment:
      - MIX_ENV=prod
      - PORT=4000
